src/components/CodeEditorWindow/config/Rules.js
src/components/CodeEditorWindow/index.js
src/components/CodeEditorWindow/parser.test.js

RUN lens is always displayed and doesn't blink on code change anymore

refactor code, make `run` lense proper display and follow code changes

---

.eslintrc.yml
.github/workflows/eslint.yml
package-lock.json
package.json
src/components/CodeEditorWindow/index.js
src/components/Logo.js
src/components/ResultEditorWindow/index.js
src/components/Sidebar.js
src/routes.js

Added workflows for eslint checks and tests

Add GH actions

---

src/components/ToastNotifications/ErrorNotifier.jsx

unhandled eslint warning in the master branch.
Due to the last PR merge of `add GH actions`

Fixed Bugs (Eslint-warning)

---

src/components/CodeEditorWindow/config/Autocomplete.js
src/components/CodeEditorWindow/config/ErrorMarker.js
src/components/CodeEditorWindow/config/Rules.js
src/components/CodeEditorWindow/config/Theme.js
src/components/CodeEditorWindow/index.js
src/components/ResultEditorWindow/index.js

Defining the before the editor mounts.

Theme Related Issues 

---

src/components/CodeEditorWindow/Menu/history.js
src/components/CodeEditorWindow/Menu/index.js
src/components/CodeEditorWindow/Menu/savedCode.js
src/components/CodeEditorWindow/config/RequesFromCode.js

Saved Code Feature added

---

package-lock.json
package.json
src/common/client.js
src/components/Points/PointCard.js
src/components/Points/SimilarSerachfield.js
src/pages/Collection.js

Recomendation view data

---

src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/index.jsx
src/components/CodeEditorWindow/parser.test.js
src/components/Points/PointCard.jsx
src/setupTests.js
vite.config.jsx

control+enter hotkey to run code in console v2 

---

package-lock.json
package.json
src/common/client.js
src/components/Collections/DeleteDialog.jsx
src/pages/Collection.jsx
src/pages/Collections.jsx

- integrate JS client
- Fix pagination in collection view

Qdrant JS client

---

src/components/Points/PointCard.jsx
src/components/Points/PointImage.jsx

image-fetaure-view-point-v2

---

src/App.jsx
src/common/axios.js
src/common/client.js
src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/Menu/index.jsx
src/components/CodeEditorWindow/config/Theme.js
src/components/CodeEditorWindow/editor.css
src/components/CodeEditorWindow/index.jsx
src/components/Collections/CollectionCard.jsx
src/components/Collections/DeleteDialog.jsx
src/components/Points/PointCard.jsx
src/components/Sidebar.jsx
src/components/ToastNotifications/ErrorNotifier.jsx
src/components/authDialog/authDialog.jsx
src/context/client-context.jsx
src/context/color-context.jsx
src/index.jsx
src/pages/Collection.jsx
src/pages/Collections.jsx
src/pages/Home.jsx

ask api key if telemetry request fails with 403

---

package-lock.json
package.json
public/openapi.json
src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/Menu/savedCode.jsx
src/components/CodeEditorWindow/config/Autocomplete.js
src/components/CodeEditorWindow/config/ErrorMarker.js
src/components/CodeEditorWindow/config/RequesFromCode.js
src/components/CodeEditorWindow/config/Rules.js
src/components/CodeEditorWindow/editor.css
src/components/CodeEditorWindow/index.jsx

add autocomplete using autocomplete-openapi package

---

src/components/CodeEditorWindow/index.jsx

Fix for doubled autocomplete suggestions

Fix for doubled autocomplete suggestions

---

.gitignore
src/components/Points/PointCard.jsx
src/components/Points/PointImage.jsx
src/components/Points/PointVectors.jsx
src/pages/Collection.jsx

- Updated the Point card UI to accommodate and visually represent multiple vectors, added a component showing buttons "Show similar" for each vector
- Conducted a makeover of the Point card to improve its overall design and user experience.

Displaying Multiple Vectors in Point Card and Point Card Makeover

---

package-lock.json
package.json
src/pages/Console.jsx

https://github.com/qdrant/qdrant-web-ui/assets/7085263/4ef5487b-e861-4f89-add4-886df3249544

Added resizable panels to the console page

---

LICENSE
package.json

Fixes <https://github.com/qdrant/qdrant-web-ui/issues/57>

Add Apache 2.0 license

---

src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/Menu/savedCode.jsx
src/components/Frame/CenteredFrame.jsx
src/pages/Collection.jsx
src/pages/Collections.jsx
src/pages/Console.jsx
src/pages/Home.jsx

- Whole width console 
- Centered layout
- Fixed margins for History and SaveCode

Visual fixes

---

src/components/CodeEditorWindow/Menu/SpeedDialMenu.jsx
src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/Menu/index.jsx
src/components/CodeEditorWindow/Menu/savedCode.jsx
src/components/CodeEditorWindow/index.jsx
src/components/EditorCommon/index.jsx
src/components/Frame/CenteredFrame.jsx
src/pages/Console.jsx

Added a speed dial menu to the console page (replacing a menu at the top of the console):
https://github.com/qdrant/qdrant-web-ui/assets/7085263/e1c2c866-db57-44f4-84e0-dd506149d26c

Console speed dial

---

src/components/CodeEditorWindow/config/RequesFromCode.js
src/components/CodeEditorWindow/index.jsx
src/components/EditorCommon/config/Rules.js

Added a beautify button to the console:

[feat] Beautify button

---

src/components/CodeEditorWindow/Menu/SpeedDialMenu.jsx
src/pages/Console.jsx

Restore console code after page reloads, button to reset the console to initial state.

Restore console code after page reloads

---

package-lock.json
package.json
src/components/FilterEditorWindow/index.jsx
src/components/VisualizeEditorWindow/index.jsx
src/components/VisualizeEditorWindow/worker.js
src/pages/Home.jsx
src/pages/Visualize.jsx

> Performed dimension reduction on the n-dimensional vectors to plot them in 2D. #70 
This PR supports the reduction of the N Dimension vector to 2 D vectors by using [@saehrimnir/druidjs](https://www.npmjs.com/package/@saehrimnir/druidjs)

[ Visualization Page ] Dimension reduction

---

src/components/Snapshots/SnapshotUploadForm.jsx
src/components/Uploader/StyledDragDrop.jsx
src/components/Uploader/StyledStatusBar.jsx

This update utilizes MUI `styled` functionality which lets us use customized components without requiring explicit theme imports.

Changed custom styling of Uppy components to MUI way

---

package-lock.json
package.json
src/components/CodeEditorWindow/index.jsx
src/components/Points/PayloadEditor.jsx
src/components/Points/PointCard.jsx

Added a payload editor to let a user change the point's payload right on the collection page.
https://github.com/qdrant/qdrant-web-ui/assets/7085263/538d46dc-2093-4146-a376-d261b3610cd2

Payload Editor

---

src/components/CodeEditorWindow/index.jsx
src/components/VisualizeChart/ViewPointModal.jsx
src/pages/Visualize.jsx
src/theme/dark-theme.js
src/theme/light-theme.js

- added variants "dual" and "heading" to the Paper and Card component
- fixed some styles on the visualization page

Added variants "dual" and "heading" to the Paper and Card component

---

src/components/CodeEditorWindow/config/RequesFromCode.js

history local storage quota overflow fixed

---

src/components/CodeEditorWindow/index.jsx
src/pages/Console.jsx

https://github.com/qdrant/qdrant-web-ui/assets/84975264/5bc3ab82-0554-46ab-943d-0daa1c84fd4a
#89

Console loading effect  Added

---

src/components/Snapshots/SnapshotUploadForm.jsx

Resolves https://github.com/qdrant/qdrant-web-ui/issues/104

API key in snapshot upload request

---

src/components/VisualizeChart/index.jsx
src/components/VisualizeChart/worker.js

ref https://github.com/qdrant/qdrant-web-ui/issues/101

feat(VisualizeChart): add support object path for `color_by` fix#101

---

src/common/client.js
src/common/client.test.js
src/common/urils.test.js
src/common/utils.js
src/components/CodeEditorWindow/config/RequesFromCode.js
src/components/CodeEditorWindow/index.jsx
src/components/Common/CircularProgressWithLabel.jsx
src/components/Snapshots/SnapshotUploadForm.jsx
src/components/Snapshots/SnapshotsTab.jsx
src/components/Snapshots/SnapshotsTableRow.jsx
src/components/VisualizeChart/index.jsx

Fixes <https://github.com/qdrant/qdrant-web-ui/issues/106> and improvement:
- Implemented snapshot downloading with API key (#106 )
- Added progress bar for real-time tracking
- Refactored associated code
- Added tests
- Formatted code

Download snapshot with api key + refactoring

---

package-lock.json
package.json
src/components/InteractiveTutorial/MdxComponents/CodeBlock.jsx
src/components/InteractiveTutorial/MdxComponents/CodeBlock.test.jsx

Code blocks in the tutorial can be edited right on the page.

Editable code blocks

---

src/components/FilterEditorWindow/config/Autocomplete.js
src/components/FilterEditorWindow/index.jsx
src/components/VisualizeChart/worker.js

Fix autocomplete, sparse vector error.

---

package-lock.json
src/pages/Console.jsx

Add "Commands" tooltip on hover to the list commands Button in Console View

---

src/components/Points/PointCard.jsx
src/pages/Collection.jsx

Added a button to delete a point:

Button to deleting a point

---

src/components/Points/PointImage.jsx

Full screen mode for pictures on the point view

---

package-lock.json
src/components/Datasets/DatasetsTableHeader.jsx
src/components/Datasets/DatasetsTableRow.jsx
src/components/Datasets/ImportDatasetDialog.jsx
src/components/Sidebar/Sidebar.jsx
src/pages/Datasets.jsx
src/routes.jsx

Added a list of snapshots for demo purpose in tutorial page

Add Snapshots for Demo Collections in tutorial page

---

package-lock.json
package.json
src/common/axios.js
src/common/bigIntJSON.js
src/components/CodeEditorWindow/Menu/history.jsx
src/components/CodeEditorWindow/Menu/savedCode.jsx
src/components/CodeEditorWindow/config/RequesFromCode.js
src/components/CodeEditorWindow/index.jsx
src/components/Collections/CollectionCluster/ClusterInfo.jsx
src/components/Collections/CollectionInfo.jsx
src/components/FilterEditorWindow/config/RequestFromCode.js
src/components/InteractiveTutorial/MdxComponents/CodeBlock.jsx
src/components/Points/PayloadEditor.jsx
src/components/Points/PointCard.jsx
src/components/Points/PointVectors.jsx
src/components/ResultEditorWindow/index.jsx
src/components/Snapshots/SnapshotUploadForm.jsx
src/components/VisualizeChart/ViewPointModal.jsx
src/components/VisualizeChart/index.jsx
src/context/client-context.jsx
src/lib/update-history.js

Adding bigInt support 

---

src/components/Points/SimilarSerachfield.jsx

BigInt are not support in `MuiChipsInput`
From 
https://github.com/qdrant/qdrant-web-ui/assets/84975264/a61216c8-a0cb-4b37-9c2a-3eef8542fc41
to
https://github.com/qdrant/qdrant-web-ui/assets/84975264/47c4d0ac-560f-4118-977a-d6522621af00

Fix data type conversion issue in SimilarSerachfield component

---

src/common/utils.js
src/components/Points/DataGridList.jsx
src/components/Points/PointCard.jsx
src/components/Points/PointVectors.jsx
src/components/Points/PointsTabs.jsx
src/components/Points/SimilarSerachfield.jsx
src/pages/Collection.jsx

https://github.com/qdrant/qdrant-web-ui/assets/84975264/3fb40ca5-850e-485a-ab54-c0fdd63fa5b8

Find similar by ID or filter by payload key:value pair.

---

package-lock.json
package.json
src/components/Points/PayloadEditor.jsx

I use this dashboard to directly manage my documents. In order to double check the changes I made to the payload, I need this diff dialog:

feat: add diff dialog to review changes before saving payload

---

src/components/InteractiveTutorial/TutorialFooter.jsx

fix: prevent tutorial footer button overlap

---

src/components/Snapshots/SnapshotUploadForm.jsx

Add collection name validation in SnapshotUploadForm component

---

src/components/Points/PointsTabs.jsx

Fixes a grammatical error on the collection page when there is no points in the collection.

Fix grammar mistake

---

src/components/JwtSection/JwtForm.jsx
src/components/JwtSection/TokenValidatior.jsx
src/pages/Jwt.jsx

Add TokenValidatior component to JwtForm and generateToken function

---

package-lock.json
package.json
src/components/FilterEditorWindow/config/Autocomplete.js
src/components/FilterEditorWindow/index.jsx
src/components/Sidebar/Sidebar.jsx

Add vector name auto-complete in visualisation 

---

src/components/InteractiveTutorial/MdxPages/Index.mdx

Fix small spelling error

---

src/components/EditorCommon/config/Rules.js

feat: Add comments configuration to langConfig in Rules.js

---

src/components/InteractiveTutorial/MdxPages/Index.mdx

update interactive tutorial for language and links

---

src/components/EditorCommon/config/Rules.js

> Instead of links like this: https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/delete_points
> it should go here: https://api.qdrant.tech/api-reference/points/delete-points

Update links to documentation

---

src/components/InteractiveTutorial/MdxPages/FilteringClauses.mdx
src/components/InteractiveTutorial/MdxPages/Index.mdx
src/components/InteractiveTutorial/MdxPages/Quickstart.mdx

fix wording in Quickstart and Filtering tutorials

---

src/components/InfoBanner.jsx
src/components/Snapshots/SnapshotsTab.jsx

@generall asked for a variant of the snapshot warning as a banner.

Snapshot warning - variant with a banner

---

package-lock.json
public/openapi.json
src/components/CodeEditorWindow/config/Autocomplete.js

- Fix for duplicated autocomplete suggestions
- Changed triggering characters

Fix for duplicated autocomplete suggestions

---

package-lock.json
src/components/Points/PointVectors.jsx
src/pages/Graph.jsx

https://github.com/user-attachments/assets/61d6c95c-777f-45a5-af32-65237f19e263

feat: Add navigation to graph page from point page

---

package-lock.json
src/components/InfoBanner.jsx
src/components/Snapshots/SnapshotsTab.jsx

chore: Add Warning on the snapshot page for distributed cluster

---

src/components/InteractiveTutorial/MdxPages/Index.mdx

Apparently out MDX setup can't render tables

replace table with list

---

src/components/Collections/CollectionInfo.jsx

#179 
https://github.com/user-attachments/assets/edbb6484-5595-459c-a8d9-0219c9005125

feature : add 'trigger optimizers' button to collection info

---

src/components/Sidebar/Sidebar.jsx
src/pages/Home.jsx

depends on https://github.com/qdrant/qdrant/pull/5056

hide jwt page if special key is used

---

src/components/InteractiveTutorial/TutorialSubpages.jsx
src/components/Sidebar/Sidebar.jsx
src/pages/Welcome.jsx

1. Add homepage rocket icon
2. Keep same collection > 0 logic
3. Move items around in Tutorials
4. Add another Tutorial button.

fix homepage and sidebar

---

src/lib/common-helpers.js
src/lib/tests/common-helpers.test.js
src/pages/Datasets.jsx
src/pages/Home.jsx

Compare the current qdrant version and the qdrant version used in the datasets manifest

Check the version before displaying datasets

---

src/components/Collections/DeleteDialog.jsx

I think the current description is too verbose. So this PR.

chore: Simplify collection deletion confirmation copy

---

src/components/Snapshots/SnapshotUploadForm.jsx

fix(snapshot-upload): fix report error if snapshot upload+recovery fails

---

src/components/Uploader/StyledDragDrop.jsx

| **Before** | **After** |
|--------|------|
|![image](https://github.com/user-attachments/assets/b5bb4509-f6f6-413b-b965-2c8780edd816)|![image](https://github.com/user-attachments/assets/b7596618-87c7-4877-b836-8970a216749b)|

Drag-and-drop width fix

---

package-lock.json
package.json
src/common/client.js
src/common/client.test.js
src/components/CodeEditorWindow/config/Autocomplete.js
src/components/CodeEditorWindow/config/customSnippets.js
src/components/CodeEditorWindow/config/snippetEnhancer.js
src/components/CodeEditorWindow/config/snippetEnhancer.test.js

- Implemented a feature in the console tab to generate code snippets dynamically.
- Users can trigger snippet generation by typing the corresponding operationId.
Depends on https://github.com/qdrant/autocomplete-openapi/pull/7

feat[console]: add code snippet generation feature in codeEditorWindow

---

package-lock.json
src/components/CodeEditorWindow/Menu/CommandsDrawer/CommandDrawer.test.jsx
src/components/Collections/CollectionAliases.jsx
src/components/Collections/CollectionAliases.test.jsx
src/components/Collections/CollectionCluster/collectionCluster.test.jsx
src/components/Collections/CollectionInfo.jsx
src/components/Collections/CollectionsList.jsx
src/components/Collections/SearchQuality/searchQualityPannel.test.jsx
src/components/Collections/collectionList.test.jsx
src/components/Common/ConfirmationDialog.jsx
src/components/InteractiveTutorial/MdxComponents/MdxCodeBlock.test.jsx
src/pages/Collections.jsx

Added collection aliases to the collections list and collection info:

Show aliases

---

package-lock.json
src/components/Collections/SearchQuality/SearchQuality.jsx
src/components/Points/PointsTabs.jsx
src/lib/qdrant-entities-helpers.js

`src/components/Collections/SearchQuality/SearchQuality.jsx` has changes because I extracted some code to reuse.

Fix bug with missinterprenting hnsw_config object as a named vector
