qdrant/qdrant-web-ui

src/components/CodeEditorWindow/Menu/history.jsx, src/components/CodeEditorWindow/Menu/savedCode.jsx
This PR gets rid of the middle vertical scrollbars in the `History` and `SavedCode` drawers
=> Unwanted scrollbar

package-lock.json, package.json, src/components/CodeEditorWindow/config/RequesFromCode.js, src/components/EditorCommon/config/Rules.js
Previous implementation failed on cases like:
```
{
"a": "//b", // This is a comment.
"c": "d" // Another comment
}
```
Fixed by using specialized jsonc parser
=> correctly parse json with comments

src/components/Points/PointCard.jsx
In my previous commits, I mistakenly assumed that image URLs were always located in the `mages` payload key.  This PR fixes this error (removed the wrong condition).
=> Point images fix - removed the wrong condition

src/components/Common/CopyButton.jsx, src/components/Common/utils/snackbarOptions.jsx, src/components/Points/PayloadEditor.jsx, src/components/Points/PointCard.jsx, src/components/Points/PointVectors.jsx, src/components/Snapshots/SnapshotsTab.jsx, src/components/ToastNotifications/ErrorNotifier.jsx, src/components/VisualizeChart/ViewPointModal.jsx, src/index.jsx
We had inconsistent alert (aka snacks, aka toasts) formats across different areas. In this PR, all alerts are implemented using `notistack`, and the alert style is unified to maintain a consistent appearance.
=> Fixed consistency of alerts appearance

.github/workflows/publish-dist-packages.yml, .github/workflows/test.yml, package-lock.json, package.json
To support supply chain security, we need to create SBOMs for the packages that we build.
This adds a SPDX SBOM for the dist package. It also ensures that the qdrant-web-ui package version matches the tag that has been pushed.
To increase security, `npm audit` has been added as a test step in the PR action. Vulnerable packages have been updated. Included actions have been updated. The nodejs version is now fixed.
A prettier check is now run in the test action.
=> Create SBOM for UI

src/pages/Collections.jsx
When running Qdrant in cluster mode, the results from the `/collections` endpoint isn't consistant (order of the collections could change). It gives a weird UX pattern where button can change position when reloading the page...
To make it more predictable I propose to sort the retrieved array using the name of the collection.
Sorry if it's not the best way to do it in JS, it's not my primary language :) 
Thanks,
=> Sort collections by name on dashboard page

package-lock.json, src/components/Points/PointCard.jsx, src/components/Points/PointImage.jsx
Fixed unnecessary space on the right side when a point has no images.
Before:
After:
=> Fix empty space on the collection point view when there are no images

src/pages/Collections.jsx
Before:
On the first visit to the Qdrant web UI (aka dashboard) collections page, the user could see a red error toast and an open dialog for inserting the API key at the same time.
After:
A user sees a red error message toast above the dialog only if they already inserted the API key but get 404|401. Otherwise, they see only open dialog.
It also fixes a problem with an empty error toast here [#257](https://github.com/qdrant/cloud-pm/issues/257)
=> Show an error on 403 only if API key exists but not valid

src/components/Points/DataGridList.jsx
=> Fix for cases when long URLs push images to the next line

src/components/Snapshots/SnapshotsTab.jsx
A snapshot may have a `creation_time` that is `null`. This PR fixes a web UI crash when this is the case.
Without this PR loading the list of collection snapshots crashes the web UI rendering a fully white page. After this PR it'll show 'unknown':
=> Fix crash when snapshot description has no creation time

src/components/Sidebar/SidebarTutorialSection.jsx
=> Fix: Incorrect Arrow Direction for Expanding Tutorials Menu

src/components/ToastNotifications/ErrorNotifier.jsx, src/lib/get-error-message.js, src/pages/Collection.jsx, src/pages/Collections.jsx
Previously, we did not incorporate error messages from the API into the toast messages displayed in the user interface. Consequently, at times, users were shown empty error toasts. This PR modifies this behavior and resolves the issue.
=> Using API error messages in the interface

package-lock.json, src/components/Sidebar/Sidebar.jsx, src/components/Sidebar/SidebarTutorialSection.jsx
When the drawer is opened, the tooltips are still active. This causes the contents of the drawer to be shown twice making the tooltips unnecessary.
**Before**
**After**
=> Show Tooltips only when drawer is minimized

src/components/FilterEditorWindow/config/RequestFromCode.js, src/components/VisualizeChart/worker.js
Fix #159 
In `worker.js`, we were only checking the first point if the vector was present or not.
This would have worked if each point contained all the named vectors. But would throw an error if the first point didn't contain the queried named vector.
**The Fix**: Filter the response from `POST /collections/name/points/scroll` to strip out points with empty vectors so that only the points with the required named vector are used for further action.
=> Fix: Multiple vectors visualization does not work if not all named vectors presented

src/components/CodeEditorWindow/Menu/CommandsDrawer/CommandsDrawer.jsx, src/components/CodeEditorWindow/Menu/CommandsDrawer/CommandsTable.jsx, src/components/CodeEditorWindow/config/CommandsDrawerUtils.js
Instead of returning an empty request body when inserting commands from the side panel (like it does now), we can return the required fields in the request body. This will make the commands panel truer to its use, ie. making it easier for the developer to find and write requests.
they can just insert it from the commands panel and quickly fill in the request body values, and if they want to customize it more, the [DOCS button](https://github.com/qdrant/qdrant-web-ui/pull/142) will always be there!
- **Preview**: (wait for the GIF to load)
**Exceptions**: This won't auto-complete request bodies that can have multiple options for a single parameter [as shown below](https://qdrant.github.io/qdrant/redoc/index.html#tag/cluster/operation/update_collection_cluster) (wait for the GIF to load) …
=> Auto-Complete Required Request Body Parameters when Inserting Commands

src/components/Notifications.jsx, src/pages/Home.jsx
=> feat: Add notifications for issues.

package-lock.json, package.json
Context: I am packaging `qdrant-web-ui` for Nixpkgs.
Problem: some dependencies in our `package-lock.json` lack of the `resolved` and `integrity` fields. This is probably caused by a bug in npm (npm/cli#4263, npm/cli#6301). Nix (and probably other sandboxed builders without internet access) relies on these fields for fetching/caching the dependencies.
The solution in this PR: run [npm-lockfile-fix](https://github.com/jeslie0/npm-lockfile-fix) to add missing fields.
Possible alternative solution: delete `package-lock.json` and regenerate it from scratch, as proposed by [this comment](https://github.com/npm/cli/issues/4263#issuecomment-1173093952). The drawback is that it will bump a lot of dependencies versions. Not sure if we want to do this right now.
---
Other changes in this PR:
- Run …
=> fix: add missing fields to package-lock.json and bump version

src/components/Notifications.jsx
Fixes the following tooltip text:
=> Fix toggle notifications tooltip text

src/components/FilterEditorWindow/config/RequestFromCode.js, src/components/VisualizeChart/index.jsx, src/components/VisualizeChart/worker.js, src/pages/Visualize.jsx
=> fix axios and allow umap visualization

src/components/Collections/SearchQuality/SearchQuality.jsx, src/components/Collections/SearchQuality/SearchQualityPanel.jsx, src/components/Collections/SearchQuality/check-index-precision.js, src/components/EditorCommon/index.jsx, src/components/FilterEditorWindow/index.jsx
Quality check timeout and small fixes
=> Quality check timeout

src/components/Points/PointImage.jsx
Just adds a few more common image extensions to the test regex in `PointImage`.
```typescript
function isImgUrl(string) {
let url;
try {
url = new URL(string);
} catch (_) {
return false;
}
if (url) {
return /\.(jpg|jpeg|png|webp|bmp|gif|ico|svg)$/.test(url.pathname);
}
return false;
}
```
=> add more image extensions to PointImage test regex

package-lock.json, src/components/Common/CodeBlock.jsx, src/components/InteractiveTutorial/MdxComponents/MdxCodeBlock.jsx
https://github.com/user-attachments/assets/6bf8a8a6-73f3-45ad-8847-d2032e3a7560
```bash
PUT collections/food/snapshots/recover 
{
"location": "https://snapshots.qdrant.io/midlib.snapshot"
}
```
=> feat: Add loading state to RunButton in CodeBlock component

src/components/Points/PointsTabs.jsx, src/components/Points/SimilarSerachfield.jsx
Fix for allowing search filters to contain colon characters ":" which is useful for values such as Windows filepaths.
This PR fixes the following issue: [https://github.com/qdrant/qdrant-web-ui/issues/218](https://github.com/qdrant/qdrant-web-ui/issues/218).
Also, fixed a bug where a JSON error would happen when clicking "Load More" if a search filter was active.
=> Similarity search field now accepts key:value filters that contain colon ":" in the value + fix bug on "Load More" when search filter is active

package-lock.json
Bump the `cross-spawn` dependency to fix https://avd.aquasec.com/nvd/2024/cve-2024-21538/
=> Bump cross-spawn to 7.0.6

package-lock.json, src/components/Snapshots/SnapshotsTab.jsx
https://github.com/user-attachments/assets/8e9bc5cb-dd26-4c1d-9822-c7a8ac242875
=> fix(snapshot-tab): fix loading issue and disable take snapshot if a process in already running

src/components/VisualizeChart/renderBy.js, src/components/VisualizeChart/requestData.js, src/components/VisualizeChart/worker.js, src/pages/Visualize.jsx
- Updated the Visualize tab to use the using parameter for consistency with other tabs.
- Added documentation for color_by.query in the Visualize tab.
fixes : #251
=> chore[visualize-tab]: fix inconsistency in Visualize tab and add documentation

src/App.jsx, src/context/color-context.jsx, src/pages/Home.jsx
=> Auto theme mode added
